### ISSUE TITLE
Unused neurons

### ISSUE THREAD

**Issue by Titanosaurus** [celiasmith/mind_field_stilwell_brain#1]
The 35, 36 and 37 neurons of the cortical model are unused. They are not conected to the V2 layer in any way, so either they are disposable (I don't think so, since they encode a lot of unused information from the retinal layer) or a few neurons from the V2 layer have been forgotten and need to be added.

I'm trying to create an interactive version for people to play with so it would be very important to have the cortical model as consistent as possible.

**Comment by celiasmith** [comment]
I suspect that these are disposable (for the purposes of the recognizable numbers for this model).  This means that none of the defined/recognizable numbers have a horizontal line on the left/middle of the 2nd from the bottom position (which seems plausible).  

As mentioned in the readme, this model just happens to be the one we used in the tv show, it's definitely unable to classify some inputs that we'd consider 'valid' (i.e. look like a number... for instance, a somewhat small 2 up and to the left would not be captured).  Note also that various cells were deleted simply so we had as many cells as people :)

**Comment by celiasmith** [comment]
Feel free to reopen if you have more questions.
